# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pages Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: git config --global user.name "github-actions[bot]"
    - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --include=dev
    - run: npm run build
    - run: cp -r build/* ./
    - run: git add .
    - run: git stash
    - run: git fetch origin
    - run: git checkout gh-pages
    - run: git stash pop
    - run: git add .
    - run: git commit -m "Deployed to gh-pages"
    - run: git push origin gh-pages
